version: '3'
services:
  web:
    user: wagtail

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3:rw

    # environment:
    #   - DJANGO_SETTINGS_MODULE=mysite.settings.production