version: '3'
services:
  web:
    user: root

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    volumes:
      - .:/app
    # environment:
    #   - DJANGO_SETTINGS_MODULE=mysite.settings.production