# Generated by Django 4.2.1 on 2023-05-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_fichier_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='enfants',
            field=models.ManyToManyField(blank=True, related_name='parents', to='dashboard.fichier'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichier_enfants', to='dashboard.fichier'),
        ),
    ]
