# Generated by Django 4.2.1 on 2023-05-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0002_alter_architecture_evaluation_metrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='model_type',
            field=models.CharField(default='CNN', max_length=100),
        ),
    ]
