# Generated by Django 4.2.1 on 2023-05-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0005_contextmodel_patients'),
        ('architecture', '0003_alter_architecture_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='contextModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context.contextmodel'),
        ),
    ]
