# Generated by Django 4.2.1 on 2023-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualisationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.CharField(max_length=500)),
                ('visualisation', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'VisualisationModel',
            },
        ),
    ]
