# Generated by Django 4.2.1 on 2023-05-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadingData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingdirectory',
            name='csv_files',
        ),
    ]
