# Generated by Django 4.2.1 on 2023-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadingData', '0002_remove_workingdirectory_csv_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingdirectory',
            name='csv_files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
