# Generated by Django 4.2.1 on 2023-05-10 10:23

from django.db import migrations, models
import loadingData.models


class Migration(migrations.Migration):

    dependencies = [
        ('loadingData', '0003_workingdirectory_csv_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingdirectory',
            name='labels',
            field=models.FileField(null=True, upload_to=loadingData.models.upload_to),
        ),
        migrations.AddField(
            model_name='workingdirectory',
            name='location',
            field=models.FileField(null=True, upload_to=loadingData.models.upload_to),
        ),
    ]
