# Generated by Django 4.2.1 on 2023-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadingData', '0004_workingdirectory_labels_workingdirectory_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePerso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='workingdirectory',
            name='workingFiles',
            field=models.ManyToManyField(blank=True, to='loadingData.fileperso'),
        ),
    ]
