# Generated by Django 4.2.1 on 2023-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadingData', '0006_fileperso_user_alter_fileperso_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileperso',
            name='numExp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workingdirectory',
            name='numExp',
            field=models.IntegerField(default=1),
        ),
    ]
