# Generated by Django 4.2.1 on 2023-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadingData', '0007_fileperso_numexp_workingdirectory_numexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileperso',
            name='numExp',
            field=models.IntegerField(default=0),
        ),
    ]
