# Generated by Django 4.2.1 on 2023-05-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadingData', '0008_alter_fileperso_numexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingpage',
            name='model',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
