# Generated by Django 4.2.1 on 2023-06-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_featuresmodel_functions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresmodel',
            name='files',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='featuresmodel',
            name='functions',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
