# Generated by Django 4.2.1 on 2023-06-22 14:14

from django.db import migrations, models
import features.models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_featuresmodel_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresmodel',
            name='addFiles',
            field=models.FileField(max_length=650, null=True, upload_to=features.models.upload_to),
        ),
    ]
