# Generated by Django 4.2.1 on 2023-06-22 14:24

from django.db import migrations, models
import features.models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_featuresmodel_addfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addFiles', models.FileField(max_length=650, upload_to=features.models.upload_to)),
            ],
            options={
                'verbose_name_plural': 'AddFormModel',
            },
        ),
        migrations.RemoveField(
            model_name='featuresmodel',
            name='addFiles',
        ),
    ]
