# Generated by Django 4.2.1 on 2023-07-06 09:43

from django.db import migrations, models
import features.models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_addformmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addformmodel',
            name='addFiles',
            field=models.FileField(max_length=800, upload_to=features.models.upload_to),
        ),
    ]
