# Generated by Django 4.2.1 on 2023-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montage', models.CharField(max_length=100)),
                ('electrode', models.CharField(max_length=100)),
                ('frequences', models.CharField(max_length=100)),
                ('frequence_max', models.PositiveIntegerField()),
                ('nombre_epochs', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'ContextModel',
            },
        ),
    ]
