# Generated by Django 4.2.1 on 2023-05-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_contextmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contextmodel',
            old_name='electrode',
            new_name='electrodes',
        ),
    ]
