# Generated by Django 4.2.1 on 2023-05-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadingData', '0008_alter_fileperso_numexp'),
        ('context', '0003_rename_electrode_contextmodel_electrodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextmodel',
            name='features',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contextmodel',
            name='workingDirectory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loadingData.workingdirectory'),
        ),
    ]
