# Generated by Django 4.2.1 on 2023-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_contextmodel_features_contextmodel_workingdirectory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextmodel',
            name='patients',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
