# Generated by Django 4.2.1 on 2023-07-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0006_contextmodel_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextmodel',
            name='raw',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
