# Generated by Django 4.2.1 on 2023-07-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0007_contextmodel_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextmodel',
            name='raw',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
